# Generated by Django 2.2.3 on 2019-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arstist', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
